//! Envelope helpers for BigBear vendor adapter plugins (protocol v1).
//!
//! Scope: the JSON envelope that crosses the host <-> guest boundary, plus payload
//! builders for the `submit` / `query` / `cancel` operations. The WIT world itself
//! (`../../wit/vendor-adapter.wit`) is generated by `wit-bindgen` in your own crate;
//! this crate deliberately does not depend on `wit-bindgen` so it also compiles for
//! host-side tests and for the `bgx-adapter dev` harness.
//!
//! Closed sets (operations, protocol major) are read from the repo-wide contract
//! `packages/app-contracts/v1/vendor-adapter.json` at compile time (INV-CONTRACT-SSOT).
//! There is no second hand-written copy of those values in this crate.
//! Guest wasm is no_std; this crate uses only alloc (no OnceLock / std).

#![cfg_attr(target_arch = "wasm32", no_std)]

extern crate alloc;

use alloc::string::{String, ToString};
use alloc::vec::Vec;
use alloc::format;

use serde::{Deserialize, Serialize};

const CONTRACT_JSON: &str = include_str!("../../../../../app-contracts/v1/vendor-adapter.json");

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct ContractFile {
    protocol_host_major: u32,
    operations: Vec<String>,
    capability_slots: Vec<String>,
}

fn contract() -> ContractFile {
    serde_json::from_str(CONTRACT_JSON).expect("vendor-adapter.json is part of this crate")
}

/// Protocol major the host speaks. Echo it back in every response.
pub fn protocol_host_major() -> u32 {
    contract().protocol_host_major
}

/// The only operations a guest may be asked to handle.
pub fn operations() -> Vec<String> {
    contract().operations
}

/// The only capability slots a manifest may declare.
pub fn capability_slots() -> Vec<String> {
    contract().capability_slots
}

/// Host -> guest envelope. Field names are the wire names; do not rename.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Invocation {
    pub protocol_version: u32,
    pub operation: String,
    pub profile_id: String,
    pub capability_slot: String,
    pub request_id: String,
    pub deadline_ms: u64,
    /// Operation payload, already schema-validated by the host.
    pub payload_json: String,
    #[serde(default)]
    pub negotiated_version: Option<u32>,
    #[serde(default)]
    pub enabled_features: Vec<String>,
}

impl Invocation {
    /// Parse `payload_json` into your own request type.
    pub fn payload<T: serde::de::DeserializeOwned>(&self) -> Result<T, serde_json::Error> {
        serde_json::from_str(&self.payload_json)
    }

    pub fn feature_enabled(&self, feature: &str) -> bool {
        self.enabled_features.iter().any(|f| f == feature)
    }

    pub fn validate(&self) -> Result<(), String> {
        if !operations().iter().any(|o| o == &self.operation) {
            return Err(format!("unknown operation: {}", self.operation));
        }
        if !capability_slots().iter().any(|s| s == &self.capability_slot) {
            return Err(format!("unknown capability slot: {}", self.capability_slot));
        }
        Ok(())
    }
}

/// Guest -> host error body. `code` must be one of the contract `errorCodes`;
/// the host maps it to user-facing copy, so never put machine detail in `message`
/// that a user is expected to act on.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AdapterError {
    pub code: String,
    pub message: String,
    pub retryable: bool,
    #[serde(default)]
    pub vendor_code: Option<String>,
    #[serde(default)]
    pub vendor_request_id: Option<String>,
}

/// Guest -> host envelope. Exactly one of `data_json` / `error` is set.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Response {
    pub protocol_version: u32,
    pub operation: String,
    #[serde(default)]
    pub data_json: Option<String>,
    #[serde(default)]
    pub error: Option<AdapterError>,
}

impl Response {
    pub fn ok(operation: &str, data: &serde_json::Value) -> Self {
        Self {
            protocol_version: protocol_host_major(),
            operation: operation.to_string(),
            data_json: Some(data.to_string()),
            error: None,
        }
    }

    pub fn err(operation: &str, code: &str, message: &str, retryable: bool) -> Self {
        Self {
            protocol_version: protocol_host_major(),
            operation: operation.to_string(),
            data_json: None,
            error: Some(AdapterError {
                code: code.to_string(),
                message: message.to_string(),
                retryable,
                vendor_code: None,
                vendor_request_id: None,
            }),
        }
    }

    /// Reject envelopes that are both successful and failed (or neither).
    pub fn validate(&self) -> Result<(), String> {
        match (self.data_json.is_some(), self.error.is_some()) {
            (true, false) | (false, true) => Ok(()),
            _ => Err("response must be either data or error".to_string()),
        }
    }
}

/// Opaque widget / field id inside the plugin. Empty strings are rejected at construction.
/// The host never interprets this string as a vendor node type.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ParamBinding(String);

impl ParamBinding {
    pub fn new(id: &str) -> Result<Self, String> {
        let t = id.trim();
        if t.is_empty() {
            return Err("ParamBinding refuses empty id".into());
        }
        Ok(Self(t.to_string()))
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

/// One RCD parameter. `range` / `enum` cannot be built without a binding.
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct RcdParam {
    pub mode: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub value: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub min: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub step: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub default: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub options: Option<Vec<serde_json::Value>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub binding_id: Option<String>,
}

impl RcdParam {
    pub fn fixed(value: serde_json::Value) -> Self {
        Self {
            mode: "fixed".into(),
            value: Some(value),
            min: None,
            max: None,
            step: None,
            default: None,
            options: None,
            binding_id: None,
        }
    }

    pub fn range(min: f64, max: f64, step: f64, default: f64, binding: ParamBinding) -> Self {
        Self {
            mode: "range".into(),
            value: None,
            min: Some(min),
            max: Some(max),
            step: Some(step),
            default: Some(serde_json::Value::from(default)),
            options: None,
            binding_id: Some(binding.as_str().to_string()),
        }
    }

    pub fn enum_of(
        options: Vec<serde_json::Value>,
        default: serde_json::Value,
        binding: ParamBinding,
    ) -> Self {
        Self {
            mode: "enum".into(),
            value: None,
            min: None,
            max: None,
            step: None,
            default: Some(default),
            options: Some(options),
            binding_id: Some(binding.as_str().to_string()),
        }
    }
}

/// Values actually written into the vendor request (INV-VENDOR-ADAPTER-RCD-12).
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct AppliedParams {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub duration: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub fps: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub resolution: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub aspect: Option<serde_json::Value>,
}

impl AppliedParams {
    pub fn to_json(&self) -> Result<serde_json::Value, serde_json::Error> {
        serde_json::to_value(self)
    }
}

fn ok_serialized(op: &str, value: &impl Serialize) -> Response {
    match serde_json::to_value(value) {
        Ok(v) => Response::ok(op, &v),
        Err(e) => Response::err(
            op,
            "adapterBadOutput",
            &format!("{op} serialize: {e}"),
            false,
        ),
    }
}

/// `submit` result: the vendor either accepted an async task or finished inline.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", tag = "kind", rename_all_fields = "camelCase")]
pub enum SubmitResult {
    /// Async: host will poll `query` with this id and can resume it after a restart.
    Accepted {
        vendor_task_id: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        applied_params: Option<serde_json::Value>,
    },
    /// Sync: outputs are final.
    Completed {
        outputs: Vec<Output>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        applied_params: Option<serde_json::Value>,
    },
}

/// `query` result for an async task.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct QueryResult {
    /// One of the contract `taskStatuses`.
    pub status: String,
    #[serde(default)]
    pub outputs: Vec<Output>,
    #[serde(default)]
    pub progress_text: Option<String>,
}

/// One produced artifact. `source` is one of the contract `outputSources`.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Output {
    pub media_kind: String,
    pub source: String,
    /// URL, host media handle, or base64 depending on `source`.
    pub value: String,
    #[serde(default)]
    pub mime: Option<String>,
}

/// Build the `submit` success payload for an accepted async task.
pub fn submit_accepted(vendor_task_id: impl Into<String>) -> Response {
    submit_accepted_with_applied(vendor_task_id, None)
}

/// Same as `submit_accepted`, plus the values actually applied to the vendor request.
pub fn submit_accepted_with_applied(
    vendor_task_id: impl Into<String>,
    applied: Option<AppliedParams>,
) -> Response {
    let applied_params = match applied {
        None => None,
        Some(a) => match a.to_json() {
            Ok(v) => Some(v),
            Err(e) => {
                return Response::err(
                    "submit",
                    "adapterBadOutput",
                    &format!("appliedParams serialize: {e}"),
                    false,
                )
            }
        },
    };
    let result = SubmitResult::Accepted {
        vendor_task_id: vendor_task_id.into(),
        applied_params,
    };
    ok_serialized("submit", &result)
}

/// Build the `submit` success payload for a request the vendor finished inline.
pub fn submit_completed(outputs: Vec<Output>) -> Response {
    submit_completed_with_applied(outputs, None)
}

pub fn submit_completed_with_applied(
    outputs: Vec<Output>,
    applied: Option<AppliedParams>,
) -> Response {
    let applied_params = match applied {
        None => None,
        Some(a) => match a.to_json() {
            Ok(v) => Some(v),
            Err(e) => {
                return Response::err(
                    "submit",
                    "adapterBadOutput",
                    &format!("appliedParams serialize: {e}"),
                    false,
                )
            }
        },
    };
    let result = SubmitResult::Completed {
        outputs,
        applied_params,
    };
    ok_serialized("submit", &result)
}

/// Build the `query` success payload.
pub fn query_result(result: &QueryResult) -> Response {
    ok_serialized("query", result)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn contract_is_readable_and_closed_sets_are_present() {
        assert_eq!(protocol_host_major(), 1);
        assert!(operations().iter().any(|o| o == "submit"));
        assert!(capability_slots().iter().any(|s| s == "imageToImage"));
    }

    #[test]
    fn invocation_parses_host_camel_case_wire_json() {
        let raw = r#"{
            "protocolVersion": 1,
            "operation": "submit",
            "profileId": "p1",
            "capabilitySlot": "image",
            "requestId": "task-1:0",
            "deadlineMs": 15000,
            "payloadJson": "{\"prompt\":\"hi\"}"
        }"#;
        let inv: Invocation = serde_json::from_str(raw).expect("wire json");
        inv.validate().expect("valid envelope");
        let payload: serde_json::Value = inv.payload().expect("payload");
        assert_eq!(payload["prompt"], "hi");
        assert!(!inv.feature_enabled("partial-outputs"));
    }

    #[test]
    fn invocation_rejects_unknown_operation() {
        let mut inv: Invocation = serde_json::from_str(
            r#"{"protocolVersion":1,"operation":"submit","profileId":"p","capabilitySlot":"image","requestId":"r","deadlineMs":1,"payloadJson":"{}"}"#,
        )
        .expect("wire json");
        inv.operation = "teleport".into();
        assert!(inv.validate().is_err());
    }

    #[test]
    fn submit_accepted_emits_vendor_task_id() {
        let resp = submit_accepted("t-42");
        resp.validate().expect("mutually exclusive");
        let data: serde_json::Value =
            serde_json::from_str(resp.data_json.as_deref().expect("data")).expect("data json");
        assert_eq!(data["kind"], "accepted");
        assert_eq!(data["vendorTaskId"], "t-42");
    }

    #[test]
    fn param_binding_rejects_empty() {
        assert!(ParamBinding::new("  ").is_err());
        assert!(ParamBinding::new("node-6").is_ok());
        let p = RcdParam::range(1.0, 15.0, 1.0, 5.0, ParamBinding::new("dur").unwrap());
        assert_eq!(p.binding_id.as_deref(), Some("dur"));
    }

    #[test]
    fn submit_accepted_with_applied_is_camel_case() {
        let mut applied = AppliedParams::default();
        applied.duration = Some(serde_json::json!(5));
        let resp = submit_accepted_with_applied("t-1", Some(applied));
        let data: serde_json::Value =
            serde_json::from_str(resp.data_json.as_deref().expect("data")).expect("data json");
        assert_eq!(data["appliedParams"]["duration"], 5);
    }

    #[test]
    fn error_response_has_no_data() {
        let resp = Response::err("submit", "adapterVendorHttpError", "upstream 500", true);
        resp.validate().expect("mutually exclusive");
        assert!(resp.data_json.is_none());
    }
}
